datasource:
  Ec2:
    timeout : 50
    max_wait : 120
    metadata_urls:
     - http://169.254.169.254:80
     - http://instance-data:8773

package_upgrade: true
apt:
  sources:
    docker.list:
      source: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
      keyid: 7EA0A9C3F273FCD8
    kubernetes.list:
      source: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
      keyid: 6A030B21BA07F4FB